export interface ExtracurricularEvent {
  id: number;
  name: string;
  description: string;
  category: string;
  type: string;
  deadline: string;
  location: string;
  virtual: boolean;
  website: string;
  difficulty: string;
  timeCommitment: string;
  image: string;
  skillzoNote: string;
}

export const extracurricularEvents: ExtracurricularEvent[] = [
  {
    id: 1,
    name: "National Science Olympiad",
    description: "Compete in science and engineering challenges with students nationwide. Perfect for building technical skills and teamwork.",
    category: "STEM",
    type: "Competition",
    deadline: "2025-12-15",
    location: "Various States",
    virtual: false,
    website: "https://www.soinc.org/",
    difficulty: "Advanced",
    timeCommitment: "3-6 months",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Develops problem-solving and collaboration skills essential for future entrepreneurs."
  },
  {
    id: 2,
    name: "Model United Nations",
    description: "Develop diplomatic skills, public speaking, and global awareness while addressing world issues.",
    category: "Leadership",
    type: "Conference",
    deadline: "2025-11-30",
    location: "Multiple Cities",
    virtual: true,
    website: "https://www.nmun.org/",
    difficulty: "Intermediate",
    timeCommitment: "2-4 months",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Builds leadership and communication skills while fostering global perspective."
  },
  {
    id: 3,
    name: "DECA Business Competition",
    description: "Showcase your business acumen in marketing, finance, and entrepreneurship. Directly aligned with Skillzo's mission.",
    category: "Business",
    type: "Competition",
    deadline: "2025-12-01",
    location: "State & National",
    virtual: false,
    website: "https://www.deca.org/",
    difficulty: "Intermediate",
    timeCommitment: "4-8 months",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Perfect for aspiring entrepreneurs - builds real business skills and networks."
  },
  {
    id: 4,
    name: "Congressional App Challenge",
    description: "Create an app to serve your community and compete nationally. Use technology for social impact.",
    category: "STEM",
    type: "Competition",
    deadline: "2025-11-01",
    location: "Virtual",
    virtual: true,
    website: "https://www.congressionalappchallenge.us/",
    difficulty: "Advanced",
    timeCommitment: "2-3 months",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Combines technical skills with social impact - core to Skillzo's values."
  },
  {
    id: 5,
    name: "Youth Leadership Development Programs",
    description: "Connect with like-minded peers and develop leadership skills through various national programs.",
    category: "Leadership",
    type: "Program",
    deadline: "2025-10-20",
    location: "Various Locations",
    virtual: true,
    website: "https://youthleadership.org/",
    difficulty: "Beginner",
    timeCommitment: "1-3 months",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Builds foundational leadership skills for creating community change."
  },
  {
    id: 6,
    name: "National Honor Society",
    description: "Demonstrate academic excellence while engaging in meaningful community service projects.",
    category: "Community Service",
    type: "Honor Society",
    deadline: "2025-09-30",
    location: "School-based",
    virtual: false,
    website: "https://www.nhs.us/",
    difficulty: "Intermediate",
    timeCommitment: "Full Academic Year",
    image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Develops service leadership and academic excellence - key Skillzo values."
  },
  {
    id: 7,
    name: "Social Innovation Challenge",
    description: "Design solutions to tackle real-world social problems. Create impact in your community.",
    category: "Social Impact",
    type: "Competition",
    deadline: "2025-03-15",
    location: "Virtual & Local",
    virtual: true,
    website: "https://socialinnovation.org/",
    difficulty: "Intermediate",
    timeCommitment: "3-4 months",
    image: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Directly aligns with Skillzo's mission of empowering students to create change."
  },
  {
    id: 8,
    name: "Future Business Leaders of America",
    description: "Develop business and leadership skills through competitions and real-world experiences.",
    category: "Business",
    type: "Organization",
    deadline: "2025-01-15",
    location: "State & National",
    virtual: false,
    website: "https://www.fbla-pbl.org/",
    difficulty: "Beginner",
    timeCommitment: "Full Academic Year",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Builds entrepreneurial mindset and business skills from high school."
  },
  {
    id: 9,
    name: "Skills USA",
    description: "Compete in technical, professional, and leadership skills competitions across various career fields.",
    category: "STEM",
    type: "Competition",
    deadline: "2025-02-28",
    location: "State & National",
    virtual: false,
    website: "https://www.skillsusa.org/",
    difficulty: "Intermediate",
    timeCommitment: "4-6 months",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Develops technical excellence and professional skills for future career success."
  },
  {
    id: 10,
    name: "Youth Climate Action Summit",
    description: "Join young activists working on climate solutions and environmental sustainability projects.",
    category: "Social Impact",
    type: "Summit",
    deadline: "2025-04-15",
    location: "Virtual & Regional",
    virtual: true,
    website: "https://youthclimate.org/",
    difficulty: "Beginner",
    timeCommitment: "1-2 months",
    image: "https://images.unsplash.com/photo-1569163139394-de4e4f43e4e5?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Empowers students to create environmental change in their communities."
  },
  {
    id: 11,
    name: "Google Code-in (GCI)",
    description: "Open source development program for pre-university students to contribute to real-world projects.",
    category: "STEM",
    type: "Program",
    deadline: "2025-02-01",
    location: "Virtual",
    virtual: true,
    website: "https://codein.withgoogle.com/",
    difficulty: "Advanced",
    timeCommitment: "2-3 months",
    image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Builds real programming skills while contributing to global open-source projects."
  },
  {
    id: 12,
    name: "National Debate Championship",
    description: "Sharpen your argumentation and public speaking skills in competitive debate formats.",
    category: "Leadership",
    type: "Competition",
    deadline: "2025-01-30",
    location: "Various States",
    virtual: false,
    website: "https://nationaldebate.org/",
    difficulty: "Intermediate",
    timeCommitment: "6-8 months",
    image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Develops critical thinking and communication skills essential for future leaders."
  },
  {
    id: 13,
    name: "Diamond Challenge",
    description: "Global high school entrepreneurship competition for innovative business concepts and social ventures.",
    category: "Business",
    type: "Competition",
    deadline: "2025-01-31",
    location: "Global (India eligible)",
    virtual: true,
    website: "https://diamondchallenge.org/",
    difficulty: "Advanced",
    timeCommitment: "4-6 months",
    image: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Perfect platform for Indian students to showcase entrepreneurial skills globally."
  },
  {
    id: 14,
    name: "Google Science Fair",
    description: "Global online science and engineering competition for students aged 13-18, including virtual participation.",
    category: "STEM",
    type: "Competition",
    deadline: "2025-05-15",
    location: "Global (Virtual)",
    virtual: true,
    website: "https://www.googlesciencefair.com/",
    difficulty: "Advanced",
    timeCommitment: "3-8 months",
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Enables Indian students to compete globally in STEM innovation."
  },
  {
    id: 15,
    name: "International Youth Math Challenge",
    description: "Global mathematics competition fostering problem-solving skills and mathematical thinking.",
    category: "STEM",
    type: "Competition",
    deadline: "2025-03-30",
    location: "Global (India eligible)",
    virtual: true,
    website: "https://iymc.info/",
    difficulty: "Intermediate",
    timeCommitment: "2-3 months",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Great opportunity for Indian students strong in mathematics to compete internationally."
  },
  {
    id: 16,
    name: "John Locke Institute Essay Competition",
    description: "International essay competition covering philosophy, politics, economics, psychology, and more.",
    category: "Leadership",
    type: "Competition",
    deadline: "2025-06-30",
    location: "Global (India eligible)",
    virtual: true,
    website: "https://www.johnlockeinstitute.com/",
    difficulty: "Advanced",
    timeCommitment: "2-4 months",
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Develops critical thinking and academic writing skills for Indian students."
  },
  {
    id: 17,
    name: "World Scholar's Cup",
    description: "Global academic competition celebrating learning across multiple disciplines with Indian participation.",
    category: "Leadership",
    type: "Competition",
    deadline: "2025-04-15",
    location: "Global (India rounds)",
    virtual: false,
    website: "https://www.worldscholarscup.org/",
    difficulty: "Intermediate",
    timeCommitment: "4-6 months",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Builds collaborative learning and global awareness for Indian students."
  },
  {
    id: 18,
    name: "International Astronomy and Astrophysics Competition",
    description: "Global competition in astronomy and astrophysics for high school students worldwide.",
    category: "STEM",
    type: "Competition",
    deadline: "2025-03-01",
    location: "Global (India eligible)",
    virtual: true,
    website: "https://iaac.space/",
    difficulty: "Advanced",
    timeCommitment: "3-5 months",
    image: "https://images.unsplash.com/photo-1446776653964-20c1d3a81b06?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Perfect for Indian students passionate about space science and astronomy."
  },
  {
    id: 19,
    name: "Global Social Entrepreneurship Competition",
    description: "International competition for students creating social impact ventures and sustainable solutions.",
    category: "Social Impact",
    type: "Competition",
    deadline: "2025-02-28",
    location: "Global (India eligible)",
    virtual: true,
    website: "https://gsec.org/",
    difficulty: "Intermediate",
    timeCommitment: "3-6 months",
    image: "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Aligns with Skillzo's mission - empowering Indian students to create social change."
  },
  {
    id: 20,
    name: "NASA Space Settlement Design Competition",
    description: "International competition to design space settlements, open to students worldwide including India.",
    category: "STEM",
    type: "Competition",
    deadline: "2025-03-15",
    location: "Global (India eligible)",
    virtual: true,
    website: "http://settlement.arc.nasa.gov/Contest/",
    difficulty: "Advanced",
    timeCommitment: "4-8 months",
    image: "https://images.unsplash.com/photo-1517976487492-5750f3195933?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Inspiring Indian students to think big about space exploration and engineering."
  },
  {
    id: 21,
    name: "International Economics Olympiad",
    description: "Global economics competition testing analytical and problem-solving skills in economics.",
    category: "Business",
    type: "Competition",
    deadline: "2025-01-15",
    location: "Global (India team)",
    virtual: false,
    website: "https://www.econolympiad.org/",
    difficulty: "Advanced",
    timeCommitment: "6-12 months",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Excellent for Indian students interested in economics and policy analysis."
  },
  {
    id: 22,
    name: "Climate Change AI Innovation Challenge",
    description: "Global challenge using AI/ML to address climate change, welcoming participants from India.",
    category: "Social Impact",
    type: "Competition",
    deadline: "2025-04-30",
    location: "Global (Virtual)",
    virtual: true,
    website: "https://climatechange.ai/",
    difficulty: "Advanced",
    timeCommitment: "3-6 months",
    image: "https://images.unsplash.com/photo-1569163139394-de4e4f43e4e5?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Combines AI skills with environmental impact - perfect for tech-savvy Indian students."
  },
  {
    id: 23,
    name: "Harvard International Review Academic Writing Contest",
    description: "International writing competition on global affairs, economics, and policy, open to Indian students.",
    category: "Leadership",
    type: "Competition",
    deadline: "2025-02-15",
    location: "Global (India eligible)",
    virtual: true,
    website: "https://hir.harvard.edu/",
    difficulty: "Advanced",
    timeCommitment: "2-4 months",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Develops policy analysis and academic writing skills for Indian students."
  },
  {
    id: 24,
    name: "International Sustainable World Energy Engineering Environment Project",
    description: "Global STEM competition focused on sustainable energy solutions, encouraging Indian participation.",
    category: "STEM",
    type: "Competition",
    deadline: "2025-05-01",
    location: "Global (India eligible)",
    virtual: true,
    website: "https://www.sweeep.org/",
    difficulty: "Advanced",
    timeCommitment: "4-8 months",
    image: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=500&h=300&fit=crop&crop=center",
    skillzoNote: "Perfect for Indian students passionate about sustainable technology and engineering."
  }
];

export const categories = ["All", "STEM", "Leadership", "Business", "Social Impact", "Community Service"];
export const types = ["All", "Competition", "Conference", "Program", "Honor Society", "Organization", "Summit"];
export const difficulties = ["All", "Beginner", "Intermediate", "Advanced"];